### ISSUE TITLE
Staff picture sizes need to change, totally unclear of how to do that on the backend

### ISSUE THREAD

**Issue by SarahStadlerBusFed** [partnerandpartners/alliance-for-youth-action#29]
We've tried to change the sizes of the staff pictures and make them into gifs. Because there's no coding in the text region on that page, we'll need some guidance on how to make that happen. It also doesn't look like it's a plugin.

**Comment by gregmihalko** [comment]
Good catch, these actually do need to be pulled in to the front-end in place of the placeholders but there will be a way to upload gifs. Visually, we were thinking that these photos would all be the same aspect ratio. If it needs to be something other than a square, that should work!

Also, we won't be installing any third-party plugins aside from the few that we know to be well-maintained and augment the core functionality (i.e. Advanced Custom Fields, etc). In general, plugins become a maintenance and security issue on Wordpress sites. Let us know if there's something that you've used in the past that we should consider implementing.

**Comment by gregmihalko** [comment]
@SarahStadlerBusFed you should be able to update the staff images now, and upload gifs in the same field if you need to. 

![screen shot 2017-03-29 at 11 34 49 am](https://cloud.githubusercontent.com/assets/3373339/24463086/beb16244-1473-11e7-965c-4781b627b2ea.png)

We'll adjust the layout per #31 and the images could most likely get a bit bigger. I should note, that in order to pull in a GIF through the backend, we'll need to query for the 'full resolution' uploads here. So it's important that these staff photos aren't more than 900KB and are sized appropriately (max of 640px by 640px) to ensure that the page loads quickly!
